version: "3.9"
services:
  influxdb:
    image: "influxdb:1.8"
    restart: always
    env_file:
      - ./influxdb-provisioning/influxdb.env
    ports:
      - "8086:8086"
    volumes:
      - type: volume
        source: influxdb
        target: /var/lib/influxdb
      - ./influxdb-provisioning/:/etc/influxdb

  influxdb-config:
    image: "influxdb:1.8"
    env_file:
      - ./influxdb-provisioning/influxdb.env
    command: influx -host influxdb -execute 'CREATE DATABASE pi'
    depends_on:
      - influxdb
    restart: on-failure
  grafana:
    image: grafana/grafana:9.3.0-beta1
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=pi
      - GF_SECURITY_ADMIN_PASSWORD=SecurePassword2137
      - GF_PATHS_CONFIG=/etc/grafana/provisioning/config.ini
  reader:
    build: .
    depends_on:
      - influxdb-config
    devices:
      - "/dev/i2c-${DEVICE_PORT:-1}:/dev/i2c-${DEVICE_PORT:-1}"
    environment:
      - DEVICE_PORT=${DEVICE_PORT:-1}
      - DEVICE_ADDRESS=${DEVICE_ADDRESS:-0x76}
      - POOLING_INTERVAL=${POLLING_INTERVAL:-5}
      - SIMULATION_MODE=${SIMULATION_MODE:-no}
      - INFLUXDB_URL=${INFLUXDB_URL:-http://influxdb:8086}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-cJ6YQc3-8I43zA6V6tns5adjjCV0-176kWEoRhIolxVdjArSpYYrUaZ0Bv7_oJSP4tQhaG7RyiOb-ZJ2rG0iqw==}
volumes:
  influxdb:
  grafana:
